version: '3'
services:
  myapplication:
    image: myapp:1.0
    environment:
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
    ports:
      - 3000:3000
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2